In [ ]:
import numpy as np
import time

n = 10

# Lists
list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result_list = [list1[i] + list2[i] for i in range(n)]
list_time = time.time() - start

# NumPy Arrays
arr1 = np.arange(n)
arr2 = np.arange(n)

start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start

print(f"List Time  : {list_time:.6f} sec")
print(f"NumPy Time : {numpy_time:.6f} sec")
print(f"NumPy is approximately {list_time/numpy_time:.2f}x faster")

List Time  : 27.792344 sec
NumPy Time : 0.051417 sec
NumPy is approximately 540.53x faster


In [3]:
import numpy as np

In [4]:
arr = np.array([[[]]])

In [5]:
arr

array([], shape=(1, 1, 0), dtype=float64)

In [6]:
print(arr)

[]


In [7]:
arr = np.array([1,2,3,4,5,6])

In [8]:
print(arr)
arr

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [9]:
arr3 = np.empty((3,3))

In [10]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr = np.linspace(0.1, 1, num=50, endpoint=True, retstep=True)

In [18]:
arr

(array([0.1       , 0.11836735, 0.13673469, 0.15510204, 0.17346939,
        0.19183673, 0.21020408, 0.22857143, 0.24693878, 0.26530612,
        0.28367347, 0.30204082, 0.32040816, 0.33877551, 0.35714286,
        0.3755102 , 0.39387755, 0.4122449 , 0.43061224, 0.44897959,
        0.46734694, 0.48571429, 0.50408163, 0.52244898, 0.54081633,
        0.55918367, 0.57755102, 0.59591837, 0.61428571, 0.63265306,
        0.65102041, 0.66938776, 0.6877551 , 0.70612245, 0.7244898 ,
        0.74285714, 0.76122449, 0.77959184, 0.79795918, 0.81632653,
        0.83469388, 0.85306122, 0.87142857, 0.88979592, 0.90816327,
        0.92653061, 0.94489796, 0.96326531, 0.98163265, 1.        ]),
 np.float64(0.018367346938775512))

In [19]:
import numpy as np

### Array Functions

In [42]:
arr = np.array([[[1,2,3,4,5,6]]])

In [43]:
arr

array([[[1, 2, 3, 4, 5, 6]]])

In [22]:
print(arr)

[1 2 3 4 5 6]


In [ ]:
np.zeros((10,15), np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [24]:
np.ones((2,3), np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [37]:
np.eye(5, 5,k=2)# we can change which diogonal to make 1 by using k

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.identity(5) # we can not change which diogonal to make 1, and we can only make square matrix here

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.empty((2,3))

array([[3.47739925e-081, 1.06187621e-046, 1.48446979e-076],
       [1.09374850e-042, 1.03096871e-071, 7.56571288e-307]])

### array attributes

In [44]:
arr.shape

(1, 1, 6)

In [45]:
arr.size

6

In [46]:
arr.ndim

3

In [47]:
arr.dtype

dtype('int64')

### Array functions

In [48]:
np.arange(1,50,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [54]:
np.linspace(1, 10, 5, endpoint=False, retstep=True)

(array([1. , 2.8, 4.6, 6.4, 8.2]), np.float64(1.8))