In [11]:
import numpy as np


In [12]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(data[0]+data[1])

[30 50 70 60]


In [13]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(data[0]*data[1])

[ 200  600 1200  800]


In [14]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(data[0]-data[1])

[-10 -10 -10  20]


In [15]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(20+data)

[[30 40 50 60]
 [40 50 60 40]]


In [16]:
data = np.array([
    [10,20,30,40],
    [20,30,40,20]
    ])
print(np.square(data))

[[ 100  400  900 1600]
 [ 400  900 1600  400]]


In [17]:
print(np.sqrt(data))

[[3.16227766 4.47213595 5.47722558 6.32455532]
 [4.47213595 5.47722558 6.32455532 4.47213595]]
