In [2]:
import numpy as np

a = np.array([[
              [1,2],
              [3,4],
              ],
              [
                [5,6],
                [7,8],
                ]])

print(a.shape)
print(a.ndim) #
print(a[1,1,1])
print(a[1,0,1])
print(a[-1,-2,-2])
print(a[-2,-1,-2])
print(a[-2,-2,-1])

# slicing
print(a[:1,0:,0:])
print(a[1:,0:,0:])
print(a[0:,:1,0:])

(2, 2, 2)
3
8
6
5
3
2
[[[1 2]
  [3 4]]]
[[[5 6]
  [7 8]]]
[[[1 2]]

 [[5 6]]]


In [3]:
print(a[:1,0:,0:])

[[[1 2]
  [3 4]]]


In [ ]:
print(a[1:,0:,0:])