In [879]:
import numpy as np

In [880]:

arr=np.array([1,2,34,4,56,6,70,8,90,18,14,16,])
# np.reshape(arr,(3,4))
arr.reshape((4,-1))
arr.reshape((-1,4))

array([[ 1,  2, 34,  4],
       [56,  6, 70,  8],
       [90, 18, 14, 16]])

In [881]:
a = np.array([12,2,4,5])
b = np.array([5,7,92,0])

np.concatenate((a,b))

array([12,  2,  4,  5,  5,  7, 92,  0])

In [882]:
a = np.array([[12,2,4,5],[2,3,6,8]])
b = np.array([[5,7,92,0],[6,99,29,19]])

np.concatenate((a,b),axis=1)

array([[12,  2,  4,  5,  5,  7, 92,  0],
       [ 2,  3,  6,  8,  6, 99, 29, 19]])

In [883]:

np.concatenate((a,b),axis=0)

array([[12,  2,  4,  5],
       [ 2,  3,  6,  8],
       [ 5,  7, 92,  0],
       [ 6, 99, 29, 19]])

In [884]:

np.concatenate((a,b),axis=None)

array([12,  2,  4,  5,  2,  3,  6,  8,  5,  7, 92,  0,  6, 99, 29, 19])

In [885]:
np.unique(a)

array([ 2,  3,  4,  5,  6,  8, 12])

In [886]:
np.count_nonzero(b)

np.int64(7)

In [887]:
size = np.size(b)
count = np.count_nonzero(b)
print(size-count)

1


In [888]:
np.unique(b).size


8

In [889]:
np.unique_counts(b)

UniqueCountsResult(values=array([ 0,  5,  6,  7, 19, 29, 92, 99]), counts=array([1, 1, 1, 1, 1, 1, 1, 1]))

In [890]:
arr = np.array([0,0,0,6,72,8,0,8,801,0,0,0,0])
np.trim_zeros(arr)

array([  6,  72,   8,   0,   8, 801])

In [891]:
np.trim_zeros(arr,trim='fb')

array([  6,  72,   8,   0,   8, 801])

In [892]:
np.trim_zeros(arr,trim='f')

array([  6,  72,   8,   0,   8, 801,   0,   0,   0,   0])

In [893]:
np.trim_zeros(arr,trim='b')

array([  0,   0,   0,   6,  72,   8,   0,   8, 801])

In [894]:
a = np.copy(arr)

In [895]:
b = arr.view()

In [896]:
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50])

# Create a view
b = arr.view()

print("Original array:", arr)
print("View array:", b)

# Modify the view
b[2] = 99

print("\nAfter modifying the view:")
print("Original array:", arr)
print("View array:", b)

Original array: [10 20 30 40 50]
View array: [10 20 30 40 50]

After modifying the view:
Original array: [10 20 99 40 50]
View array: [10 20 99 40 50]


In [897]:
import numpy as np

# Original array
arr = np.array([10, 20, 30, 40, 50])

# Create a copy
c = arr.copy()

print("Original array:", arr)
print("Copied array:", c)

# Modify the copy
c[2] = 99

print("\nAfter modifying the copy:")
print("Original array:", arr)
print("Copied array:", c)

Original array: [10 20 30 40 50]
Copied array: [10 20 30 40 50]

After modifying the copy:
Original array: [10 20 30 40 50]
Copied array: [10 20 99 40 50]


In [898]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

np.setxor1d(a,b)

array([1, 2, 3, 7, 8, 9])

In [899]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3])

In [900]:
a = np.array([1,2,3,4,5,6])
b = np.array([4,5,6,7,8,9])

np.setdiff1d(b,a)

array([7, 8, 9])

Multiplication


In [901]:
np.dot(a,b)

np.int64(154)

In [902]:
a = np.array([[12,2],[2,3]])
b = np.array([[5,7],[6,99]])


In [903]:
np.dot(a,b)

array([[ 72, 282],
       [ 28, 311]])

In [904]:
a = np.array([[[12,2,8],[2,3,4],[9,8,9]]])
b = np.array([[[5,7,4],[6,99,3],[10,23,2]]])
np.cross(a,b)

array([[[ -48,   -8,   74],
        [-387,   18,  180],
        [-191,   72,  127]]])

In [905]:
a= np.array([1,2,3])
b = np.array([4,5,6])
np.cross(a,b)

array([-3,  6, -3])

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5,6],[7,8,9]])
np.cross(arr1,arr2)



array([[-3,  6, -3],
       [-3,  6, -3]])

In [907]:
print(a @ b)

32
