In [162]:
import numpy as np

In [163]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[4,5,6],[7,8,9]])

In [164]:
np.add(arr1,arr2)

array([[ 5,  7,  9],
       [11, 13, 15]])

In [165]:
np.subtract(arr1,arr2)

array([[-3, -3, -3],
       [-3, -3, -3]])

In [166]:
np.divide(arr1,arr2)

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667]])

In [167]:
np.multiply(arr1,arr2)

array([[ 4, 10, 18],
       [28, 40, 54]])

In [168]:
np.square(arr1,arr2)

array([[ 1,  4,  9],
       [16, 25, 36]])

In [169]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [170]:
np.exp(arr1)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [171]:
np.log(arr1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [172]:
np.power(arr1,arr2)

array([[                   1,                   16,                19683],
       [          4294967296,   298023223876953125, -5108087961858080768]])

In [173]:
np.sin(arr1)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [174]:
np.cos(arr1)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [175]:
np.abs(arr1,arr2)

array([[1, 2, 3],
       [4, 5, 6]])