Random Functionss

In [1]:
import numpy as np

In [2]:
#1)
np.random.rand(5)

array([0.9541041 , 0.65175693, 0.87859865, 0.05317087, 0.20465702])

In [3]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[1 0 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 1 0 1]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 1 0 0 1 0]
 [0 0 0 0 1 0 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 1]
 [0 0 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 1 0]]


In [4]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[9, 4, 4],
       [1, 9, 6]], dtype=int8)

In [5]:
np.random.randint(1,90,(10,10),np.int8)

array([[22, 54, 45, 64,  5, 38, 84, 50, 78, 12],
       [54, 13,  4, 59, 89, 19, 38, 83, 61, 61],
       [68, 27, 64, 40, 32,  6, 59, 52, 55, 29],
       [61, 58,  1, 74, 84, 75, 74, 66, 22, 85],
       [82, 33, 86, 79, 41,  4, 12, 56, 32, 48],
       [31, 13, 81, 42, 76, 69, 54, 49, 61,  4],
       [29, 79, 23, 52, 36, 86, 21, 74, 86, 19],
       [61, 43, 32, 61, 12, 85, 25, 57, 25, 59],
       [54, 40, 20, 45, 55,  1, 57, 54, 21, 27],
       [41, 24, 16, 76, 81, 22, 69,  7, 48, 78]], dtype=int8)

In [6]:
np.random.randint(90)

79

In [7]:
np.random.randint(5,10)

6

In [8]:
np.random.randint(5,10,8)


array([5, 7, 6, 8, 6, 9, 6, 5], dtype=int32)