Random Functions

In [ ]:
import numpy as np

In [71]:
#1)
np.random.rand(5)

array([0.46295395, 0.57333762, 0.14877784, 0.08255856, 0.05421307])

In [ ]:
#2)

a = [0, 1]

arr = np.random.choice(a, size=(10, 10), replace=True, p=[0.8, 0.2])

print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 1]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 1]
 [1 1 0 0 1 0 0 0 0 0]
 [0 0 1 0 1 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 1 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 1 1 1 0 0 0 0 0]]


In [ ]:
#3)
np.random.randint(1,10,(2,3),np.int8)

array([[6, 2, 3],
       [6, 9, 5]], dtype=int8)

In [ ]:
np.random.randint(1,90,(10,10),np.int8)

array([[ 8, 75, 69, 72, 27, 71, 41, 53, 84, 71],
       [13, 60, 61, 83, 66, 21, 30, 73, 70, 73],
       [ 8, 42, 48, 75,  7, 73, 47, 39, 76, 30],
       [51, 67, 74, 22, 60, 85, 27, 67, 23, 15],
       [81, 23, 51,  5, 70, 48, 53, 57, 48, 13],
       [76, 54,  9, 78, 39, 54,  2, 12, 18, 55],
       [14, 49, 11,  5, 53, 36,  3, 33, 82, 36],
       [47, 11, 17,  6, 37, 52, 64,  7, 28, 17],
       [60, 62, 83, 79, 69, 65, 85, 44, 78, 11],
       [ 5, 84, 13, 89, 41, 77, 46, 85, 20, 73]], dtype=int8)

In [ ]:
np.random.randint(90)

28

In [ ]:
np.random.randint(5,10)

8

In [ ]:
np.random.randint(5,10,8)

array([8, 6, 9, 7, 7, 8, 9, 6], dtype=int32)

In [78]:
a = [1,2,3,4,[5,6,7],8,9]
print(a[0:4])

print(a[4][1])

[1, 2, 3, 4]
6


In [79]:
arr = np.array([1,2,4,5,6,7,7,8,8])
arr[2]

np.int64(4)